### ISSUE TITLE
Extend the postgres adapter

### ISSUE THREAD

**Issue by teeparham** [rgeo/activerecord-postgis-adapter#129]
It seems like it would be cleaner to simply extend the existing Postgresql adapter rather than extending that adapter and renaming it to "postgis".

This would obviously require a major version bump.

See discussion at https://github.com/rgeo/activerecord-postgis-adapter/issues/14

**Comment by sauy7** [comment]
I don't know what the answer to this is but I've just had to fork the money-rails gem because it was sniffing for "postgresql" or "activerecord-jdbcpostgresql-adapter" in order to work around the "money" type in AR42.

https://github.com/Travellersmatch/money-rails/commit/c7d3e391b4969a344f25d8df71b8821201983f68

It seems whichever way you go it leaves a code smell somewhere.
