### ISSUE TITLE
running on Heroku

### ISSUE THREAD

**Issue by andyvb** [rgeo/activerecord-postgis-adapter#14]
Have you tried running your adapter on Heroku?  Out of the box you end up needing to modify the Heroku config variable DATABASE_URL to use the 'postgis' adapter.  Wondering if you had any suggestions on how to do this without editing the DATABASE_URL, so things like heroku pg:promote still works.

**Comment by omphe** [comment]
I got this working successfully on Heroku with the following in my puma.rb
```
on_worker_boot do
  if defined?(ActiveRecord::Base)
    config = ActiveRecord::Base.configurations[Rails.env] ||
        Rails.application.config.database_configuration[Rails.env]
    config['adapter'] = 'postgis'
    ActiveRecord::Base.establish_connection(config)
  end
    end

on_restart do
  if defined?(ActiveRecord::Base)
    config = ActiveRecord::Base.configurations[Rails.env] ||
        Rails.application.config.database_configuration[Rails.env]
    config['adapter'] = 'postgis'
    ActiveRecord::Base.establish_connection(config)
  end
end
```

**Comment by blackjid** [comment]
This looks like a very old issue, but it's still a problem. I'm using rails 4.1.16 and activerecord-postgis-adapter 2.x

This has been working for me, in the `url` property in the `database.yml` file I just replace the adapter before passing it to the configuration:

```yml
# config/database.yml
production:
  ...
  url: <%= ENV.fetch("DATABASE_URL", "").gsub(/postgres/, 'postgis') %>
```

**Comment by Drowze** [comment]
I am using the same setup @blackjid which is working flawlessly so far.

I really would like not to version database.yml though, since it contains the local database credentials (it was on my .gitignore) so I am not _that_ happy with the solution.  
What I am doing right now is pushing simply what is needed to heroku and then running `git update-index --assume-unchanged config/database.yml`, so I can edit it with no much trouble, though trying to checkout old branches that had no database.yml present had led me to some trouble :cry:

**Comment by softwaregravy** [comment]
@Drowze The recommended way to set up your database.yml is to use environment variables that are set in your config. This issue is specifically concerning Heroku, so I'll refer you to the configs. https://devcenter.heroku.com/articles/config-vars 

Your database.yml shouldn't contain any production credentials.

**Comment by hirowatari** [comment]
> ```yaml
> <%= ENV.fetch("DATABASE_URL", "").gsub(/postgres/, 'postgis') %>
> ```
You might prefer `<%= ENV.fetch('DATABASE_URL').gsub(/postgres/, 'postgis') %>` to avoid silently ignoring that your DATABASE_URL is missing.

**Comment by mjy** [comment]
Perhaps we need a wiki with current standards/gotchas/setup information on Heroku?  Maybe someone who uses it can stepup and confirm their setup so we can close this issue?

At minimum we could 1) start a Heroku wiki page and two cross-reference to this closed issue?

**Comment by keithdoggett** [comment]
I've set up this [wiki](https://github.com/rgeo/activerecord-postgis-adapter/wiki/Heroku) that just cross-references this.

If someone wants to make a proper wiki with the info @mjy mentioned that would be great, but I'm going to close the issue now.

**Comment by gagalago** [comment]
After having again this issue, I just update quickly the wiki. feel free to continue to improve it :tada:
