### ISSUE TITLE
postgis-adapter loading time is slow

### ISSUE THREAD

**Issue by clashman** [rgeo/activerecord-postgis-adapter#153]
Requiring 'activerecord-postgis-adapter' takes my decent machine more than a second to pass, which, at least to me, appears insanely slow. I this expected behavior?

**Comment by teeparham** [comment]
It takes 600ms on my machine. Yes, that's slow. Please investigate.

**Comment by rovermicrover** [comment]
From my own investigation
ruby (2.2.1)
rails (4.1.10)
activerecord-postgis-adapter (2.2.1)
rgeo-activerecord (1.2.0)

```
puts Benchmark.measure { require 'activerecord-postgis-adapter' }
  0.500000   0.070000   0.570000 (  0.579998)
```

```
puts Benchmark.measure { require 'rgeo/active_record' }
  0.450000   0.070000   0.520000 (  0.524749)

puts Benchmark.measure { require 'activerecord-postgis-adapter' }
  0.040000   0.010000   0.050000 (  0.046620)
```

It would seem that the load time isn't in this gem but rather rego-activerecord. From
https://github.com/rgeo/rgeo-activerecord/blob/master/lib/rgeo/active_record.rb
```
require 'rgeo'
require 'active_record'
require 'rgeo/active_record/version'
require 'rgeo/active_record/spatial_expressions'
require 'rgeo/active_record/arel_spatial_queries'
require 'rgeo/active_record/common_adapter_elements'
require 'rgeo/active_record/ar_factory_settings'
require 'rgeo/active_record/geometry_mixin'
```
If I require each one of these at a time these are the benchmark results I get
```
puts Benchmark.measure { require 'rgeo' }
  0.100000   0.020000   0.120000 (  0.126690)

puts Benchmark.measure { require 'active_record' }
  0.140000   0.020000   0.160000 (  0.159803)

puts Benchmark.measure { require 'rgeo/active_record/version' }
  0.000000   0.000000   0.000000 (  0.004382)

puts Benchmark.measure { require 'rgeo/active_record/spatial_expressions' }
  0.000000   0.000000   0.000000 (  0.001725)

puts Benchmark.measure { require 'rgeo/active_record/arel_spatial_queries' }
  0.000000   0.000000   0.000000 (  0.001826)

puts Benchmark.measure { require 'rgeo/active_record/common_adapter_elements' }
  0.160000   0.020000   0.180000 (  0.182496)

puts Benchmark.measure { require 'rgeo/active_record/ar_factory_settings' }
  0.000000   0.000000   0.000000 (  0.000821)

puts Benchmark.measure { require 'rgeo/active_record/geometry_mixin' }
  0.000000   0.000000   0.000000 (  0.000675)
```

Which adds up to just under 480 MS. There really isn't anyway to get past the 130 MS from rgeo or the 160ms from ActiveRecrod. The only part that seems to maybe have some room to clean up is the load time in 'rgeo/active_record/common_adapter_elements'.

Now with 

ruby (2.2.1)
rails (4.2.1)
activerecord-postgis-adapter (3.0.0.beta2)
rgeo-activerecord (2.1.1)

```
puts Benchmark.measure { require 'rgeo/active_record' }
  0.490000   0.070000   0.560000 (  0.565732)

puts Benchmark.measure { require 'activerecord-postgis-adapter' }
  0.050000   0.020000   0.070000 (  0.068527)
```

```
puts Benchmark.measure { require 'rgeo' }
  0.100000   0.020000   0.120000 (  0.118487)

puts Benchmark.measure { require 'active_record' }
  0.150000   0.020000   0.170000 (  0.178557)

puts Benchmark.measure { require 'rgeo/active_record/version' }
  0.000000   0.000000   0.000000 (  0.005895)

puts Benchmark.measure { require 'rgeo/active_record/spatial_expressions' }
  0.010000   0.000000   0.010000 (  0.002472)

puts Benchmark.measure { require 'rgeo/active_record/arel_spatial_queries' }
  0.000000   0.000000   0.000000 (  0.001523)

puts Benchmark.measure { require 'rgeo/active_record/common_adapter_elements' }
  0.000000   0.000000   0.000000 (  0.002217)

puts Benchmark.measure { require 'rgeo/active_record/ar_factory_settings' }
  0.140000   0.020000   0.160000 (  0.165266)

puts Benchmark.measure { require 'rgeo/active_record/geometry_mixin' }
  0.000000   0.000000   0.000000 (  0.000769)
```

This time with the beta and new version of rgeo-activerecrod the only targetable delay is from ar_factory_settings. The only changes to ar_factory_settings between these two versions seem to be only cosmetic, but the module GeoSchemaDumper was removed from the common_adapter_elements. So it must be something that the module GeoSchemaDumper causes to be required that causes the load time. With the newer version because module GeoSchemaDumper is no longer there to cause it to be required, the culprit is now instead caused to be required by something in ar_factory_settings. This is of course assuming both delays are caused by the same underlying thing.

That is as far as I have had time to trace down the load times.

**Comment by teeparham** [comment]
Thank you for doing the analysis of require times. We may be able to get rid of the dependency on the `rgeo-activerecord` gem entirely.

**Comment by teeparham** [comment]
Update: it's faster now. Anecdotal evidence with latest master:

```
$ irb
> require 'benchmark'
> puts Benchmark.measure { require 'active_record' }
  0.150000   0.020000   0.170000 (  0.180318)

> puts Benchmark.measure { require 'rgeo' }
  0.120000   0.010000   0.130000 (  0.142402)

> puts Benchmark.measure { require 'activerecord-postgis-adapter' }
  0.230000   0.040000   0.270000 (  0.263559)
```

**Comment by teeparham** [comment]
Closing as stale. Performance improvements are always welcome.
