### ISSUE TITLE
Collumn type migration when updating from 2.x to 3.x

### ISSUE THREAD

**Issue by steffenix** [rgeo/activerecord-postgis-adapter#172]
As I have update active record to 4.2, I have to update the postgis adapter.
I would like to use `st_point` instead of `point` so I've created a migration and it fails.

 `change_column :region_points, :lonlat, :st_point, geographic: true`

I get PG::UndefinedObject: ERROR:  type "st_point" does not exist

**Comment by teeparham** [comment]
You do not need to change the column type in a migration when you upgrade the adapter to 3.0 since the column type in the database is the same. Only the syntax for specifying the column type in migrations has changed. 

After upgrading the gem, run `rake db:schema:dump` to dump the schema in the new format. Your schema should be the same if you're using a SQL structure (`structure.sql`), and may be slightly different if you're using a ruby schema file (`schema.rb`).

**Comment by steffenix** [comment]
Thank for the advice.

**Comment by klappradla** [comment]
I was on the verge of changing it by hand. Thanks a lot!

**Comment by srgoldman** [comment]
This saved me a ton of time, thanks!
