### ISSUE TITLE
Support for Rails 5

### ISSUE THREAD

**Issue by tommyblue** [rgeo/activerecord-postgis-adapter#196]
The gemspec file locks `activerecord` at `4.x` but rails 5 uses `5.x`.
Do you have plans to update the gem to work with rails 5 before it becomes stable?

**Comment by jsquirrelz** [comment]
@teeparham I'd also be interested to know what you're imagining for Rails 5. I'd be down to lend a hand.

**Comment by teeparham** [comment]
Step 1: 787bfab6c96

**Comment by pitamonster** [comment]
I feel bad chiming in because I'm pretty sure I'm not a developed enough developer to lend a hand, but I'm loving Rails 5 and I'd also be interested in knowing what the plans are/timeline is for Rails 5 support.

**Comment by afn** [comment]
Another issue is that `ActiveRecord::ConnectionHandling::VALID_CONN_PARAMS` was removed in https://github.com/rails/rails/commit/83e00c642b16b7b56d1e6a732b55be4a2e9997df. I'll open a PR shortly.

**Comment by pitamonster** [comment]
I am getting the following error any time the gem tried to load with AR 5:

Bundler::GemRequireError: There was an error while trying to load the gem 'activerecord-postgis-adapter'.
...
NoMethodError: undefined method `attribute_types_cached_by_default' for ActiveRecord::Base:Class
Did you mean?  attribute_type_decorations
/usr/local/rvm/gems/ruby-2.3.0/gems/activerecord-5.0.0.beta1/lib/active_record/dynamic_matchers.rb:21:in `method_missing'
/usr/local/rvm/gems/ruby-2.3.0/gems/rgeo-activerecord-0.5.0/lib/rgeo/active_record/common_adapter_elements.rb:169:in `<module:ActiveRecord>'
/usr/local/rvm/gems/ruby-2.3.0/gems/rgeo-activerecord-0.5.0/lib/rgeo/active_record/common_adapter_elements.rb:47:in `<module:RGeo>'
/usr/local/rvm/gems/ruby-2.3.0/gems/rgeo-activerecord-0.5.0/lib/rgeo/active_record/common_adapter_elements.rb:45:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.0/gems/rgeo-activerecord-0.5.0/lib/rgeo/active_record.rb:81:in `require'
...

So I think the rgeo-activerecord gem is calling an AR method deprecated in Rails 5? I can also see that the rgeo-activerecord version is locked at 0.5.0--which is old? Could later versions of rgeo-activerecord maybe not call the deprecated method, but still work with activerecord-postgis-adapter? I'm not putting question marks because I'm generally obnoxious, but because I don't exactly know what I'm saying. So please let me know if there is other information I can provide that would be more relevant/helpful.

Again, thank you so much for all that you do.

**Comment by afn** [comment]
I've started work on https://github.com/amitree/activerecord-postgis-adapter/tree/rails-5 but I'm hitting a snag: the `new_column` method no longer gets the table name as a parameter, so we can't call `spatial_column_info` from here. Any thoughts on how to rewrite this for Rails 5?

**Comment by afn** [comment]
@pitamonster try using

    gem 'rgeo-activerecord', github: 'amitree/rgeo-activerecord'

**Comment by afn** [comment]
I've made quite a bit of progress here: #204. Not quite ready yet, but it's getting close. Right now the issue I'm working on is that `rake db:schema:dump` doesn't include the `limit` data; here's a diff of `db/schema.rb` from our project:

```diff
-    t.geography "coverage_area",            limit: {:srid=>4326, :type=>"geometry", :geographic=>true}		
+    t.geography "coverage_area"
```

**Comment by pitamonster** [comment]
@afn O my gosh thank you!! I'm using your latest commit and all is well! Thank you for your hard work and your magical powers!

**Comment by teeparham** [comment]
There's now an official `rails-5` branch that uses a beta release of `rgeo-activerecord` (5.0.0.beta) that allows `activerecord` 5.0.0.beta. 

To anyone who has done work on the rails 5 update, please rebase onto that branch & submit PRs with `rails-5` as the base.

**Comment by ConorNugent** [comment]
Hi, I'm just looking into possibly to migrating my rails-api app to rails 5 and I'm running into an issue running migrations using the rails-5 branch of activerecord-postgis-adapter

  app-api git:(cn/post-gis) ✗ rake db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate
rake aborted!
ArgumentError: wrong number of arguments (given 5, expected 1..4)
/Users/conornugent/.rvm/gems/ruby-2.3.0@curio-api/bundler/gems/activerecord-postgis-adapter-85747794b98c/lib/active_record/connection_adapters/postgis/schema_statements.rb:49:in `type_to_sql'
/Users/conornugent/.rvm/gems/ruby-2.3.0@curio-api/gems/activerecord-5.0.0.beta2/lib/active_record/connection_adapters/abstract/schema_creation.rb:17:in `type_to_sql'
/Users/conornugent/.rvm/gems/ruby-2.3.0@curio-api/gems/activerecord-5.0.0.beta2/lib/active_record/connection_adapters/postgresql/schema_statements.rb:8:in `visit_ColumnDefinition'
/Users/conornugent/.rvm/gems/ruby-2.3.0@curio-api/gems/activerecord-5.0.0.beta2/lib/active_record/connection_adapters/abstract/schema_creation.rb:14:in `accept'

Maybe I'm missing something or maybe this is related to this old issue #98. This is what I have in my Gemfile 

gem 'activerecord-postgis-adapter',  :github => 'rgeo/activerecord-postgis-adapter', :branch => 'rails-5'

**Comment by teeparham** [comment]
@ConorNugent the rails-5 branch does not work yet. Pull requests are welcome.

**Comment by ConorNugent** [comment]
@teeparham No problem! I'll have a look at it and see if I can find a fix

**Comment by SpacyRicochet** [comment]
I'm having the same issue. I'm hopelessly new to Ruby on Rails and PostGIS, so won't be able to help on this.

**Comment by ConorNugent** [comment]
hey guys, I did have a look at this at one stage but I quickly realised I was out of my depth and likely to do more harm than good. Thanks so much to all the people  that were involved in sorting this out and @henriquemenezes in particular. It's massively appreciated on our end anyway

**Comment by teeparham** [comment]
Fixed by #213

**Comment by oyeanuj** [comment]
@afn I know this is an old issue but I am running into possibly a similar situation as yours. On `db:load`, migrations are erroring out here:
```rb
t.geography "coordinates", limit: {:srid=>4326, :type=>"st_point", :geographic=>true}
```
with this error message:
```sh
NoMethodError: undefined method `geography' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::TableDefinition:0x007f8142d17ef8>
```

How did you end up fixing this?

**Comment by vbrazo** [comment]
@oyeanuj I'm getting this same error message. Have you already found a solution for you?

**Comment by teeparham** [comment]
Rails 5 support was released over 3 years ago. Please open a new issue if there is one.
