### ISSUE TITLE
Add support for Rails 6

### ISSUE THREAD

**Issue by KeithP** [rgeo/activerecord-postgis-adapter#298]

**Comment by KeithP** [comment]
Need to assess what if anything needs changing to enable dependency to be bumped up to activerecord 6.0.0.
change log: https://github.com/rails/rails/blob/master/activerecord/CHANGELOG.md

**Comment by muzbox** [comment]
Is this going to happen soon?

Wanting to move to 6.0 rc1

thanks

**Comment by chemic** [comment]
any news about it?

**Comment by mcastilho** [comment]
+1

**Comment by vfonic** [comment]
Is this just not tested on Rails 6 or it doesn't work? Because currently it doesn't work for sure :) due to the dependency restriction. But from your comment it seems like it only hasn't been tested. I think the better approach would be to write in the readme to use with Rails 6 with caution and then you might also get much better error reports from people testing stuff in Rails 6.

It's also to say in the readme:
> Version 5.x supports ActiveRecord 5.1+

This led me to believe version 5 supports Rails 6 as well.

So, what's the proposed workaround for the time being? Fork the project and just change the dependency restriction? :/

**Comment by cyberjom** [comment]
Still not working for 6.0.0.rc2. Any suggestion please ?

**Comment by PhilCoggins** [comment]
Just want to point out that Rails 6 final was [released](https://github.com/rails/rails/tree/v6.0.0) today.

How close are we to having a Rails 6 compatible release? Is there anything the community can do to help support this release?

**Comment by zocoi** [comment]
There is an PR https://github.com/rgeo/activerecord-postgis-adapter/pull/300 from https://github.com/corneverbruggen/activerecord-postgis-adapter/tree/activerecord-6.0 which failed the tests right now. Hopefully the author will fix the test so it can be merged

**Comment by teeparham** [comment]
Fixed by #303
