### ISSUE TITLE
The location field of geography but  sometime as string field

### ISSUE THREAD

**Issue by anke1460** [rgeo/activerecord-postgis-adapter#333]
The location in database is public.geography(Point,4326), but i show it location.y in view file, sometimes will raise this error:

**undefined method `y' for "0101000020E6100000492EFF21FD3E5C4053245F09A4343C40":String>**

**Comment by keithdoggett** [comment]
This looks like you're having the same issue we saw here: https://github.com/rgeo/activerecord-postgis-adapter/issues/307. This was fixed with #309.

Could you tell me what version of Ruby, ActiveRecord, and Activerecord-Postgis-Adapter you're using? As well as the column definition for the problematic column if possible.

**Comment by anke1460** [comment]
Yes, these issues like me, i will upgrade my version to try it.
My Ruby version 2.5.1,  ActiveRecord 2.5.3,  Activerecord-Postgis-Adapter 5.2.2 and location field in database is geography(Point,4326).  Thanks for your reply! @keithdoggett

**Comment by keithdoggett** [comment]
Thanks for sending that. The fix was released with activerecord-postgis-adapter 6.0.1 which uses ActiveRecord 6.0+. If you're not able to upgrade to that version, I can probably merge a fix into the 5.0-stable branch.

**Comment by anke1460** [comment]
Thanks, My projects already upgrade 6.0.1. Maybe other projects which used 5.0 need fixed  it.
