### ISSUE TITLE
Help with querying all points that are within radius x from point lat and long

### ISSUE THREAD

**Issue by arthurysong** [rgeo/activerecord-postgis-adapter#372]
Hi can I get some help with building a query that does what the title says?

I have my TennisCourt model set up with the following schema

![image](https://user-images.githubusercontent.com/48899712/187047078-c32dc303-2d95-495b-a2f4-964bd0972fae.png)

I want to be able to pass in a latitude and longitude and find all tennis courts that are within X meters. . And this is what I have so far.

![image](https://user-images.githubusercontent.com/48899712/187047146-4f93b03e-fd63-4e35-9e79-9b7c23815a96.png)

**Comment by keithdoggett** [comment]
Hi @arthurysong currently this adapter doesn't support the use of spatial scopes so that you can chain `st_intersects`, for example, with other where clauses. I hope to add it at some point though.

In the meantime, you can use the arel interface to make spatial queries. See this section of the `rgeo-activerecord` documentation for help (https://github.com/rgeo/rgeo-activerecord#spatial-queries).
