### ISSUE TITLE
Error `TypeError: can't cast RGeo::Geographic::SphericalPolygonImpl` on Rails 7.2 and HEAD `activerecord-postgis-adapter`

### ISSUE THREAD

**Issue by stevegeek** [rgeo/activerecord-postgis-adapter#402]
The following reproduction script shows the error. 

It works on Rails 7.0/7.1 with the latest release of `activerecord-postgis-adapter` but fails when run with Rails 7.2 and master branch of `activerecord-postgis-adapter`

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "rails", "~> 7.2"
  # If you want to test against edge Rails replace the previous line with this:
  # gem "rails", github: "rails/rails", branch: "main"

  gem "pg"
  gem "activerecord-postgis-adapter", github: "rgeo/activerecord-postgis-adapter", branch: "master"
  gem "rgeo-activerecord", "~> 7"
end

require "active_record"
require "minitest/autorun"
require "logger"


# `createdb postgis_test_db`

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(
  "postgis://localhost/postgis_test_db"
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  enable_extension 'postgis'

  create_table :posts, force: true do |t|
    t.st_point :geo
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_geo_where
    post = Post.create!(geo: RGeo::Geos.factory(srid: 4326).point(-122, 47))
    point = post.geo
    geo_factory = RGeo::Geographic.spherical_factory(srid: 4326, buffer_resolution: 4)
    area_center = geo_factory.point(*point.coordinates)
    circle = area_center.buffer(10_000)
    polygon = geo_factory.multi_polygon([circle])
    assert_equal 1, Post.where("ST_DWithin(?, posts.geo, ?)", polygon, 1).count
  end
end
```

Exception:

```
TypeError: can't cast RGeo::Geographic::SphericalPolygonImpl
    /Users/stephen/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0/lib/active_record/connection_adapters/abstract/quoting.rb:105:in `type_cast'
    /Users/stephen/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0/lib/active_record/connection_adapters/postgresql/quoting.rb:185:in `type_cast'
    /Users/stephen/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0/lib/active_record/connection_adapters/abstract/quoting.rb:229:in `block in type_casted_binds'
    /Users/stephen/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0/lib/active_record/connection_adapters/abstract/quoting.rb:225:in `map'
    /Users/stephen/.asdf/installs/ruby/3.3.4/lib/ruby/gems/3.3.0/gems/activerecord-7.2.0/lib/active_record/connection_adapters/abstract/quoting.rb:225:in `type_casted_binds'
...
```

Thanks for all the work on the postgis adapter for Rails!

**Comment by DanielJackson-Oslo** [comment]
Same error here. Downgrading to Rails 7.1 in the meantime! 

Thank you guys for all the help, and let me know if I can chip in with any money to help you free up time for this.

**Comment by JamesChevalier** [comment]
I'm getting the same `can't cast RGeo::Geographic::SphericalLineStringImpl` error in my test suite when running it against Rails 7.2.1. I looked into it a little bit, and was able to get a little more detail - hopefully it's helpful.

The query it's running when it's hitting this error is:

```
Node.where("ST_DWITHIN(geog, ?, 25)", geog)
```

If I adjust that query to this unsafe version, it does work:

```
Node.where("ST_DWITHIN(geog, '#{geog}', 25)")
```

**Comment by StoneGod** [comment]
I have not this problem on rails 7.2.1

**Comment by jnweaver** [comment]
@JamesChevalier I have a similar experience in terms of an unsafe version of query working, but throwing an error when using the safe version. Also Rails 7.2.1.

Works:
```
details.common.where("ST_CONTAINS(way, st_transform(GeomFromEWKT('srid=4326;POINT(#{lng.to_f}  #{lat.to_f})'), 3857))")
```

Errors:
```
details.common.where("ST_CONTAINS(way, st_transform(GeomFromEWKT('srid=4326;POINT(:lng  :lat)'), 3857))", {lng: lng.to_f, lat: lat.to_f})
```
Throws: `ActiveRecord::StatementInvalid: PG::IndeterminateDatatype: ERROR:  could not determine data type of parameter $1`

**Comment by JamesChevalier** [comment]
Some additional details that 🤷 may or may not be helpful...

My initializer:
```ruby
RGEO_FACTORY = RGeo::Geographic.spherical_factory(srid: 4326, uses_lenient_assertions: true)

RGeo::ActiveRecord::SpatialFactoryStore.instance.tap do |config|
  config.default = RGEO_FACTORY
end
```

I tested with `simple_mercator_factory` and that also produced the same error.
I tested against the `bump-7-2` branch from https://github.com/rgeo/activerecord-postgis-adapter/pull/405 and that also produced the same error.

**Comment by BuonOmo** [comment]
@JamesChevalier do you have a full one file example tested against `bump-7-2`? That would be pretty useful! ([here's the activerecord template](https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record.rb))

**Comment by JamesChevalier** [comment]
Thanks for the suggestion, @BuonOmo 

```rb
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem "rails", "~> 7.2"
  gem "pg"
  gem "activerecord-postgis-adapter", github: "rgeo/activerecord-postgis-adapter", branch: "bump-7-2"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Base.establish_connection("postgis://localhost/postgis_test_db")
ActiveRecord::Schema.define do
  enable_extension "postgis"

  create_table :posts, force: true do |t|
    t.geometry :geo, geographic: true
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_geo_where
    post = Post.create!(geo: RGeo::Geographic.spherical_factory(srid: 4326, uses_lenient_assertions: true).point(-122, 47))
    assert_equal 1, Post.where("ST_DWITHIN(geog, ?, 25)", post.geo).count
  end
end
```

**Comment by BuonOmo** [comment]
Thank you! It might actually be related to the failing tests that we currently have and are blocking us from releasing this branch. I'll hopefully have a look within the next two weeks.

**Comment by jnweaver** [comment]
@BuonOmo If helpful, here's another failing one file example. This is throwing `ActiveRecord::StatementInvalid: PG::IndeterminateDatatype: ERROR:  could not determine data type of parameter $1`

Using an unsafe query instead -- commented out after the failing assertion -- passes.

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem "rails", "~> 7.2"
  gem "pg"
  gem "activerecord-postgis-adapter", github: "rgeo/activerecord-postgis-adapter", branch: "bump-7-2"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Base.establish_connection("postgis://localhost/postgis_test_db")
ActiveRecord::Schema.define do
  enable_extension "postgis"

  create_table :posts, force: true do |t|
    t.geometry :geo, limit: {srid: 3857, type: "geometry"}
  end
end

class Post < ActiveRecord::Base
end

class BugTest < Minitest::Test
  def test_geo_where
    post = Post.create!(geo: "POLYGON ((-9953167.702116467 5323537.15351723, -9953167.702116467 5323635.125782488, -9953041.625807118 5323635.125782488, -9953041.625807118 5323537.15351723, -9953167.702116467 5323537.15351723))")
		post_with_center = Post.select("ST_Y(ST_centroid(ST_transform(geo,4326))) as lat, ST_X(ST_centroid(ST_transform(geo,4326))) as lng").first
		lng = post_with_center.lng
		lat = post_with_center.lat
    assert_equal 1, Post.where("ST_CONTAINS(geo, st_transform(GeomFromEWKT('srid=4326;POINT(?  ?)'), 3857))", lng, lat).count
    # assert_equal 1, Post.where("ST_CONTAINS(geo, st_transform(GeomFromEWKT('srid=4326;POINT(#{lng} #{lat})'), 3857))").count
  end
end
```

**Comment by BuonOmo** [comment]
So it looks like this was already failing before 7.2. @jnweaver do you have a timing in history where it was not failing ? As of now the failure makes a lot of sense, there is not any overriding of type casting at all, so the code `Post.where(query, bindings)` never goes through this codebase!

@seuros @keithdoggett any idea of history related to this issue ?

**Comment by JamesChevalier** [comment]
I had a few minutes to dig into things - here are some details, in case they're helpful (apologies if I'm sharing information you already know).

activerecord v7.2 introduced [parts = [build_bound_sql_literal(opts, rest)]](https://github.com/rails/rails/blob/8e6a5deca626c944933211d7977f4e7e76869e74/activerecord/lib/active_record/relation/query_methods.rb#L1526)
Previously, the query would use [parts = [klass.sanitize_sql(rest.empty? ? opts : [opts, *rest])]](https://github.com/rails/rails/blob/8e6a5deca626c944933211d7977f4e7e76869e74/activerecord/lib/active_record/relation/query_methods.rb#L1528)

So, for a query in the format of:
```ruby
YourModel.where("ST_DWITHIN(geog, ?, 25)", geog)
```

The old version of this code would produce output like:
```
["ST_DWITHIN(geog, 'STRING_VERSION_OF_GEO_DATA', 25)"]
```

Whereas the new version of this code produces output like:
```
[#<Arel::Nodes::BoundSqlLiteral "(ST_DWITHIN(geog, ?, 25))" [#<RGeo::Geographic::SphericalLineStringImpl:0x3d554 "LINESTRING (ALL, THE, COORDINATES)">]>]
```

I don't think it's super relevant, but when the code flows through the [build_bound_sql_literal](https://github.com/rails/rails/blob/v7.2.1/activerecord/lib/active_record/relation/query_methods.rb#L1664-L1682) method, it goes into [the else branch](https://github.com/rails/rails/blob/v7.2.1/activerecord/lib/active_record/relation/query_methods.rb#L1672) where `value` is passed along without modification because `value.respond_to?(:id_for_database)` is `false`.

**Comment by JamesChevalier** [comment]
Your `PostGIS::Quoting` diff, above, does resolve the issue. It makes sense, as well, since the thing that's missing in Rails 7.2+ is the sql sanitization that was once done via `parts = [klass.sanitize_sql(rest.empty? ? opts : [opts, *rest])]`

The `sanitize_sql` code flows like:
* `sanitize_sql` calls [sanitize_sql_for_conditions](https://github.com/rails/rails/blob/v7.2.1/activerecord/lib/active_record/sanitization.rb#L8-L41)
* which in turn calls [sanitize_sql_array](https://github.com/rails/rails/blob/v7.2.1/activerecord/lib/active_record/sanitization.rb#L139-L180)
* and since the statement includes `?` it calls [replace_bind_variables](https://github.com/rails/rails/blob/v7.2.1/activerecord/lib/active_record/sanitization.rb#L202-L208)
* which then flows through [replace_bind_variable](https://github.com/rails/rails/blob/v7.2.1/activerecord/lib/active_record/sanitization.rb#L210-L216) and into [quote_bound_value](https://github.com/rails/rails/blob/v7.2.1/activerecord/lib/active_record/sanitization.rb#L232-L244) (again because of the `?`)
* finally calling [connection.quote(connection.cast_bound_value(value))](https://github.com/rails/rails/blob/v7.2.1/activerecord/lib/active_record/sanitization.rb#L242)

That last step is where we land on the logic of the commit that you linked to. That commit was specifically (if I'm understanding correctly) removing the use of `connection` in too many places. Your use of `to_s` falls in line with the spirit of the commit, in that it's also not relying on `connection`.

One thing I don't know yet is whether `when RGeo::Feature::Instance` catches all possible cases of `to_s` being needed. Based on what I've seen so far (if I'm understanding things correctly), I'd answer the question of "In which cases does activerecord-postgis-adapter need to self-sanitize?" with "All of them."

**Comment by pedantic-git** [comment]
Confirmed that https://github.com/rgeo/activerecord-postgis-adapter/issues/402#issuecomment-2372122350 resolves the issue for me too.

If anyone needs it while @BuonOmo takes the necessary time to work out a permanent and tested fix, I've put it in a branch:

```ruby
gem "activerecord-postgis-adapter", "~> 9.0", github: 'fishpercolator/activerecord-postgis-adapter', branch: 'bump-7-2-quoting-fix'
```

**Comment by navidemad** [comment]
Does someone tried to run it against the new HEAD rails 8.0.0.beta1 ?

**Comment by BuonOmo** [comment]
@pedantic-git you could open a PR :)

**Comment by pedantic-git** [comment]
@BuonOmo I certainly could, but my change is built on top of your PR branch in #405 so I thought you might like to cherry-pick the commit into that branch rather than having two PRs open with largely the same diff. Happy to open a PR if you disagree!

**Comment by BuonOmo** [comment]
@pedantic-git if your branch fixes some of the blocking failing tests, I'll cherry-pick it. Otherwise lets wait for the merging of #405 before opening a new PR indeed :)

**Comment by pedantic-git** [comment]
Thanks! Very happy to wait and offer any assistance I can in the completion of #405

**Comment by JamesChevalier** [comment]
Oops! [v10](https://rubygems.org/gems/activerecord-postgis-adapter/versions/10.0.0) was released via https://github.com/rgeo/activerecord-postgis-adapter/commit/1290093838bfcbab4688463ee45a7ae9c43d3ffe without the `PostGIS::Quoting` fix that @BuonOmo shared in https://github.com/rgeo/activerecord-postgis-adapter/issues/402#issuecomment-2371701919

**Comment by BuonOmo** [comment]
@JamesChevalier would you like to open a PR?

**Comment by pedros007** [comment]
Documenting in case someone else runs into a similar problem:

I have some code that I cannot share using activerecord-postgis-adapter-11.0.0 and does something like:

```ruby
irb(main):001> factory = RGeo::Geos.factory(srid: 4326).freeze;
irb(main):002> SomeModel.where('geom && ?', some_geometry)
(irb):1:in `<main>': FrozenError: can't modify frozen RGeo::Geos::CAPIFactory: #<RGeo::Geos::CAPIFactory:0x533e0 srid=4326 bufres=1 flags=8>
```

I can get around the error if I call `.to_s` on `some_geometry` like so:

```ruby
irb(main):002> SomeModel.where('geom && ?', some_geometry.to_s)
```

I dont understand why this happens even after v11.0.0 which has #417 .

**Comment by pedros007** [comment]
@seuros Oops, I wrote the wrong pseudocode!

```ruby
irb(main):001> factory = RGeo::Geos.factory(srid: 4326).freeze;
irb(main):002> some_geometry = factory.parse_wkt('POLYGON((0 0,0 3,1 3,1 0,0 0))')
irb(main):003> SomeModel.where('geom && ?', some_geometry)
(irb):1:in `<main>': FrozenError: can't modify frozen RGeo::Geos::CAPIFactory: #<RGeo::Geos::CAPIFactory:0x533e0 srid=4326 bufres=1 flags=8>
```

In any case, I think something with ActiveRecord-7.2 might have changed the way data is serialized through Postgres.  I put a brain dump of observations on a potentially related issue https://github.com/rgeo/activerecord-postgis-adapter/issues/431#issuecomment-3074905788
